### ISSUE TITLE
Support zxing intents

### ISSUE THREAD

**Issue by nvllsvm** [Fr4gorSoftware/SecScanQR#28]
Support zxing intents:

- text to QR - [Intent Source](https://github.com/zxing/zxing/blob/master/android-integration/src/main/java/com/google/zxing/integration/android/IntentIntegrator.java#L452-L481), [Scanner Manifest](https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L94-L97)
- QR to text - [Intent Source](https://github.com/zxing/zxing/blob/master/android-integration/src/main/java/com/google/zxing/integration/android/IntentIntegrator.java#L289-L331), [Scanner Manifest](https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L56-L59)

Apps like Syncthing (https://github.com/syncthing/syncthing-android/issues/709) are making use of this API. Adding support to SecScanQR would make it compatible with it, among others.

**Comment by Fr4gorSoftware** [comment]
SecScanQR already uses the ZXing libary. What is the benefit of your version?

**Comment by Catfriend1** [comment]
Can the zxing included library launch secscanqr or only barcode scanner? What do I need to adjust that the user can choose which app should do the qr scan?

**Comment by Roy-Orbison** [comment]
A ZXing-compatible intent has [become the de-facto standard](https://www.google.com.au/search?q=android+intent+zxing+scan+qr), with a huge number of tutorials and SO answers recommending its use; it's been around since before Android was version 1.0, but the app itself is no longer supported.  I realise that looking for `com.google.zxing.client.android.SCAN` to determine whether a QR scanner is installed is naive, but solving this at SecScanQR's end would do a lot of good for many apps.

Another example: Firefox thinks there's no QR app installed, thus no code reading from the address bar and no WiFi debugging unless this intent is available.

**Comment by Catfriend1** [comment]
Meanwhilst, binary eye from F-Droid supports the zxingi intent...

**Comment by Fr4gorSoftware** [comment]
I implemented the zxing intent but I am not sure if everything works fine because it seems like the Qr Code Scanner have to be supported from the apps.
Code can be found in the [Zxing intent](https://github.com/Fr4gorSoftware/SecScanQR/tree/XZing-intent) branch. I could not manage to build Syncthing on my machine and do the changes that were needed to test zxing intent for SecScanQR. @Catfriend1 could you do this for me? 

If I am not wrong then SecScanQR must be added in line 635 in the [DeviceActivity](https://github.com/Catfriend1/syncthing-android/blob/master/app/src/main/java/com/nutomic/syncthingandroid/activities/DeviceActivity.java) and then it should work with the version of SecScanQR in the following [branch](https://github.com/Fr4gorSoftware/SecScanQR/tree/XZing-intent)

**Comment by Roy-Orbison** [comment]
Do you have a beta APK available for download? Did you test the feature
build with Firefox? I think it only uses the ZXing intent to check for and
run a QR scan.

**Comment by Catfriend1** [comment]
You're right with the proposed change. @Fr4gorSoftware
If you can give me a little time, I can do a test build with your app ID.
What's the problem building Syncthing-Fork exactly? The repos readme has some build instructions and most requirements are auto downloaded to your build directory of not present on the machine. Are you trying on windows or linux? In the first weeks doing Syncthing I even got the build working without having AndroidStudio installed.

**Comment by Fr4gorSoftware** [comment]
@Roy-Orbison [here](https://github.com/Fr4gorSoftware/SecScanQR/blob/XZing-intent-testing/app-debug.apk) you can download the test version. I also tired Binary Eye and the test version of SecScanQR and both can not be used in Fennec F-Droid (Firefox for F-Droid).

@Catfriend1 I tried to build it with Android Studio under Linux. I get the following error message:
`Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.1-all.zip'.`

**Comment by Catfriend1** [comment]
Please provide feedback if this works:
https://drive.google.com/open?id=1IcpfU-vON0e736XzfnL-4w2c6xnWBTYH

**Comment by Fr4gorSoftware** [comment]
> Please provide feedback if this works:
> https://drive.google.com/open?id=1IcpfU-vON0e736XzfnL-4w2c6xnWBTYH

Works perfectly. Thank you for your support

**Comment by Roy-Orbison** [comment]
Thanks @Fr4gorSoftware, Wasn't able to get anything other than a 404 from that APK link, and don't see 1.2.3 on F-Droid.

Is it that Mozilla's code isn't querying correctly for generic/compatible intents in [InputOptionsUtils.java](https://github.com/mozilla/gecko-dev/blob/master/mobile/android/geckoview/src/main/java/org/mozilla/gecko/util/InputOptionsUtils.java)? I didn't see any difference between your `intent-filter` and [ZXing's](https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml).

**Comment by Fr4gorSoftware** [comment]
@Roy-Orbison I already deleted this branch with the apk because the test was already successful. F-Droid will need some days.

I guess Firefox uses something similar like Syncthing uses
