### ISSUE TITLE
Feature Request: Read QR code/Barcode from image file

### ISSUE THREAD

**Issue by Wolfram-Wolf** [Fr4gorSoftware/SecScanQR#29]
Say I send a generated barcode or QR code to someone over the Internet. By being able to process image files, the other person could scan the file to retrieve the data without having to scan the code off my phone screen.

**Comment by nahuhh** [comment]
Any luck with this?

I think the easiest way to do this is to add secscanqr to the share menu as "scan barcode"

1. Open an image
2. Select share
3. Select "scan barcode"
4. Secscan qr opens in scan mode but instead of launching the camera and reading from the camera stream, the Image opens in secscan qr scans the image 

Probably an easier/faster way to accomplish step 4.

I feel this feature should be stock in every qr code scanner. 

Use case: I'd say 99% of the qr codes I encounter are on my mobile device.
Adding an fdroid repository, setting up 2fa, offers sent in emails etc.
Currently, my workaround is to:
1. Take a screenshot
2. Use kdeconnect, casting or DLNA to share/open the image with my pc or Android tv
3. Scan the image

**Comment by Fr4gorSoftware** [comment]
hi there,
the feature is implemented since version 1.2.1

1. Open image
2. Select Share
3. Click on SecScanQR
4. Information is shown on screen if qr code could be detected

This feature uses the zxing library for that and this library does not always detect the qr code or barcode in the picture but if you create the qr code with SecScanQR you can decode it with SecScanQR again just fine.
